//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PSDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SENDMSGDLG                  102
#define ID_VIEW_SHOWLOG                 104
#define ID_VIEW_LOG                     105
#define ID_VIEW_LOBBYSERVERS            106
#define ID_ROOM_QUIT                    107
#define ID_POP_ADDTOMYBUDDYLIST         108
#define ID_ROOM_SET                     109
#define ID_POP_INVITETOROOM             110
#define ID_INVITETOROOM_ROOMS           111
#define IDR_MAINFRAME                   128
#define ID_STARTGAME                    129
#define IDD_DIALOG1                     201
#define IDD_LOGIN                       201
#define IDD_SHOWLOG                     202
#define IDR_LOGMENU                     203
#define IDD_LOBBYSERVERDLG              204
#define IDD_fileserver                  205
#define IDI_CLOSEROOMLIST               206
#define IDI_ROOM                        207
#define IDI_SERVER                      208
#define IDR_ROOMTB                      209
#define IDB_BITMAP1                     212
#define IDI_OFFLINE                     213
#define IDI_ICON2                       214
#define IDI_ONLINE                      214
#define IDI_MSG                         215
#define IDR_CHATUSERS                   216
#define IDR_BUDDY                       217
#define IDR_ROOMLIST                    218
#define IDD_CREATEROOM                  219
#define IDI_ACCOUNTID                   220
#define IDI_psuid                       221
#define IDI_VERSION                     222
#define IDI_IP                          223
#define IDI_START                       224
#define IDR_SHOWIP                      225
#define IDR_AREA                        226
#define IDD_REGISTER                    227
#define IDD_DIALOG2                     228
#define IDD_SELUSERNAME                 228
#define IDD_PROMOTE                     229
#define IDI_LOCK                        230
#define IDD_DETAILINFO                  232
#define IDD_CHANGEPASS                  233
#define IDR_TAB                         234
#define IDI_ICON1                       235
#define IDI_STARTGAME                   236
#define IDR_LOGINOPT                    237
#define IDB_BITMAP2                     238
#define IDB_SERVER                      238
#define ID_POP_LOBBYSERVER              238
#define IDC_COMBO1                      1000
#define IDC_USERNAME                    1001
#define IDC_PASSWORD                    1002
#define IDC_LOGEDIT                     1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON2                     1005
#define IDC_FILESERVER                  1005
#define IDC_BUTTON3                     1006
#define IDC_LOBBYS                      1006
#define IDC_BUTTON4                     1007
#define IDC_LIST1                       1008
#define IDC_STATIC2                     1009
#define ID_CLOSE                        1010
#define ID_LOGIN                        1011
#define IDC_MSG                         1012
#define IDC_USERS                       1013
#define IDC_BNSEND                      1014
#define IDC_ROOMNAME                    1015
#define IDC_MAXUSER                     1016
#define IDC_BUSEPASS                    1017
#define IDC_CHATTYPE                    1020
#define IDC_GAMETYPE                    1021
#define IDC_NICKNAME                    1022
#define IDC_APPID                       1023
#define IDC_SUBID                       1024
#define IDC_PASSWORD1                   1027
#define IDC_EMAIL                       1029
#define IDC_CITY                        1031
#define IDC_GENDER                      1032
#define IDC_YEAR                        1033
#define IDC_MONTH                       1034
#define IDC_DAY                         1035
#define IDC_NEWSLETTER                  1036
#define IDC_LOCATION                    1037
#define IDC_RESET                       1038
#define IDC_REGISTER                    1039
#define IDC_NAME1                       1040
#define IDC_NAME2                       1041
#define IDC_CUSUSERNAME                 1042
#define IDC_NAME3                       1043
#define IDC_NAME4                       1044
#define IDC_RADIO5                      1045
#define IDC_NAME5                       1045
#define IDC_CUSRADIO                    1047
#define ID_BNLEFT                       1048
#define ID_BNRIGHT                      1049
#define IDC_DLGDESC                     1051
#define ID_REFRESH                      1058
#define ID_MODIFY                       1059
#define IDC_OLDPASSWORD                 1060
#define IDC_Game                        1063
#define ID_LOGOUT                       32771
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_LOGPOP_COPY                  32775
#define ID_LOGPOP_COPYALL               32776
#define ID_LOGPOP_CLEAR                 32777
#define ID_POP_REMOVE                   32784
#define ID_POP_INVITETOROOM32785        32785
#define ID_INVITETOROOM_ROOMS32786      32786
#define ID_POP_CREATEROOM               32787
#define ID_POP_LOCALIP                  32788
#define ID_POP_PUBLICIP                 32789
#define ID_POP_ISIP                     32790
#define ID_POP_REFRESH                  32791
#define ID_POP_REFRESHALL               32794
#define ID_POP_REFRESHAREA              32795
#define ID_Menu                         32796
#define ID_Menu32797                    32797
#define ID_FILE_PERINFO                 32798
#define ID_FILE_LOGOUT                  32799
#define ID_FILE_CHANGEPASSWORD          32800
#define ID_POP_CLOSE                    32801
#define ID_TAB_CLOSE                    32802
#define ID_FILE_CREATEAGAMEROOM         32803
#define ID_POP_LOBBYSERVERS             32804
#define ID_POP_FILESERVERS              32805
#define ID_POP_GAMELOGIN                32806
#define ID_POP_SHOWLOG                  32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
