######################################################################
# Automatically generated by qmake (2.00a) Tue May 9 21:57:25 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += form.h temp.h
FORMS += form.ui
SOURCES += form.cpp main.cpp
