#pragma once

template <class T>
class CProxy_ICTestAtlEvents : public IConnectionPointImpl<T, &__uuidof( _ICTestAtlEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
